name: Feature request
description: Suggest features, propose improvements, discuss new ideas.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >
        Before requesting please search [existing issues](https://t.me/c/1937296927/3602).
        Do not create issues to implement new algorithms as these will be closed.
        Usage questions such as "How do I...?"  belong on the
        [Discord](https://t.me/RuslanSenatorov) and will be closed.

  - type: textarea
    attributes:
      label: "Feature description"
      description: >
        This could include new topics or improving any existing implementations.
    validations:
      required: true
